server:
  port: 9010

spring:
  application:
    name: monitor
  #允许登录监控系统的用户名和密码
  security:
    user:
      name: admin
      password: 123456
  cloud:
    consul:
      host: 192.168.1.220
      port: 8500
      discovery:
        prefer-ip-address: true

#输出监控指标用于服务监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
