server:
  port: 9001

spring:
  application:
    name: order-service
  #监控系统的授权信息
  boot:
    admin:
      client:
        username: admin
        password: 123456

feign:
  hystrix:
    #启用hystrix短路保护
    enabled: true
  okhttp:
    #feign使用okhttp来作为http客户端
    enabled: true

#输出监控指标用于服务监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
#如果要在Spring boot admin中查看日志，需要指定存储的文件
logging:
  file: ./logs/order-service.log