server:
  port: 9002

spring:
  application:
    name: storage-service
  datasource:  #数据库连接池相关配置
    url: jdbc:mysql://192.168.1.212:3306/cloud-demo-storage?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #监控系统的授权信息
  boot:
    admin:
      client:
        username: admin
        password: 123456
  cloud:
    consul:
      host: 192.168.1.220
      port: 8500
      discovery:
        prefer-ip-address: true

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true

#hystrix超时时间设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

#输出监控指标用于服务监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

#mybatis-plus框架配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #别名设置 默认类名 类名首字母小写
  type-aliases-package: com.github.davidfantasy.springclouddemo.storageservice.model,com.github.davidfantasy.springclouddemo.storageservice.dto

# Seata 配置项，对应 SeataProperties 类
seata:
  application-id: ${spring.application.name} # Seata 应用编号，默认为 ${spring.application.name}
  tx-service-group: ${spring.application.name}-group # 该应用所属事务组编号，用于寻找TC集群的映射
  # Seata 服务配置项，对应 ServiceProperties 类
  service:
    #事务分组与TC集群（seata）集群的映射关系，order-service-group对应tx-service-group参数，值为一个虚拟的TC集群名称
    #默认值就是default，如果无需分组可以不用设置
    vgroup-mapping:
      storage-service-group: default
    # Seata注册中心配置项
  registry:
    type: consul # 注册中心类型，默认为 file
    consul:
      cluster: seata #对应seata集群在consul中注册的服务名
      server-addr: 192.168.1.220:8500